# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: ubuntuVM

steps:
- script: echo $(password)
  displayName: 'try display password without map'
- script: echo $PASSWORD
  env:
   PASSWORD: $(password) # secret shoould be explicitely mapped out


 

