# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: UbuntuVM

steps:
- bash: |
    echo "the password value: $PASSWORD"
    if [ "$PASSWORD" = "passer" ];
    then echo "passer est le mot de passe"
    else 
      echo "tu dois faire un mappage explicite"
    fi
- bash: |
    echo 'Explicite mapping: "$PASSWORD_EXPLICITE"'
    if [ "$PASSWORD_EXPLICITE" = "passer" ];
    then echo "mappage reusi"
    fi
  env:
   PASSWORD_EXPLICITE: $(password)
  
